### ISSUE TITLE
ROS Workshop meeting time

### ISSUE THREAD

**Issue by AlpNov** [UH-ECE6397/Swarmathon-ROS#1]
@UH-ECE6397/students @UH-ECE6397/staff 

I'm considering moving the meeting time for the ROS workshop to Wednesday at 2:30 PM. Also, I'll be in the Robotics lab at S391 from 11 AM to 1 PM on Monday to discuss ROS. Is that ok with everybody?

**Comment by Dustyoday** [comment]
yes

On Thu, Feb 4, 2016 at 8:40 PM, An Nguyen notifications@github.com wrote:

> @UH-ECE6397/students https://github.com/orgs/UH-ECE6397/teams/students
> @UH-ECE6397/staff https://github.com/orgs/UH-ECE6397/teams/staff
> 
> I'm considering moving the meeting time for the ROS workshop to Wednesday
> at 2:30 PM. Also, I'll be in the Robotics lab at S391 from 11 AM to 1 PM on
> Monday to discuss ROS. Is that ok with everybody?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UH-ECE6397/Swarmathon-ROS/issues/1.

## 

_Gary "Dusty" O'Day_
_Control Systems Integrator_

_O'Day Instruments, LLC_
_BSEE Student of University of Houston_
_VP of Tau Beta Pi, Texas Epsilon Chapter_
https://www.linkedin.com/in/dustyoday
dusty@odayinst.com
g.l.oday@ieee.org
gloday@uh.edu
(409) 789 - 3580

**Comment by meakdogan** [comment]
Hi , you and me have power system course between 2.30pm and 4 pm on Wednesday. Will you do it in the same hour? 

Mehmet Emin Akdogan

**Comment by MCBurbage** [comment]
That works for me. 

MCB

**Comment by AlpNov** [comment]
Woops, forgot I have the power course at that time. How about Wednesday at
11 AM then?

**Comment by JavGG95** [comment]
Lol, I'm fine with that

**Comment by Jordan-M-Bowman** [comment]
Wednesday at 11 works for me.

**Comment by meakdogan** [comment]
Mehmet Emin Akdogan

**Comment by meakdogan** [comment]
It works for me as well .

Mehmet Emin Akdogan

**Comment by chandikasilva** [comment]
That works for me.

**Comment by MCBurbage** [comment]
That works for me too.
MCB

```
  From: An Nguyen <notifications@github.com>
```

 To: UH-ECE6397/Swarmathon-ROS Swarmathon-ROS@noreply.github.com 
Cc: MCBurbage mcfieler@uh.edu
 Sent: Thursday, February 4, 2016 9:09 PM
 Subject: Re: [Swarmathon-ROS] ROS Workshop meeting time (#1)

Woops, forgot I have the power course at that time. How about Wednesday at
11 AM then?

**Comment by AlpNov** [comment]
I am in S391, door is locked so just knock.
- An

**Comment by meakdogan** [comment]
Hi
Was there any meeting today or did i miss ? 

I have a problem for openin swarmathon ros. When can I ask you that problem ?
Mehmet 

Mehmet Emin Akdogan
