### ISSUE TITLE
ROS meeting Monday

### ISSUE THREAD

**Issue by AlpNov** [UH-ECE6397/Swarmathon-ROS#10]
@UH-ECE6397/students 
@UH-ECE6397/staff 

Hope you folks had a good weekend,

**Monday, Mar 7 at 11 AM** in **S391**

We're meeting to discuss the current understanding of the Swarmathon ROS code base. I'll demonstrate the physical demonstration of the robot.

We also need to look at printing out some of the april tags for the physical robots to look at. They are under the `simulation/models` folder. Each tag (or cluster of) is under their own folder, with `at` in front of them. For example, the 242nd tag will be under the `at242/materials/textures/atag-242.png`. The 8th 4-tag cluster are under `atags4_8/materials/textures/atags4_8.png`.

I'm not sure what the print scale should be. We should probably check the [forum](http://swarmathon.discussion.community/) for that.

Additionally, on **Friday Mar 25 (time TBD)** the physical team from **UH - Clear Lake** will visit and we will run a couple of friendly "matches". I'm planning to use the Engineering Common (the pit) for this, provided that the robot can get decent GPS reception in there, more testing to follow.

**Comment by AlpNov** [comment]
Hey guys,

There weren't many undergraduates at the meeting yesterday. It's exam week, so y'all gotta study. No worries.

We have started dividing up some work among the students. Each task will be created as an open issue that can be used as communication channels. Feel free to chime in if you would like to join the task.

1 - [State Machine analysis - Kaisong, Jordan and Mehmet](https://github.com/UH-ECE6397/Swarmathon-ROS/issues/13)

2 - [New messages and basic algorithm - An and Mary](https://github.com/UH-ECE6397/Swarmathon-ROS/issues/12)

3 - [Extended Kalman Filter (EKF) - Shiva and Srikanth](https://github.com/UH-ECE6397/Swarmathon-ROS/issues/11)

There are more tasks that have not been assigned, let us know if you would be interested in working on one of these:

4 - Work to extract more information out of the April Tag library (UNM is using the [April tag library](https://april.eecs.umich.edu/wiki/index.php/AprilTags-C) from the creator of Arpil tags). It seems you can extract orientation and position of the tag with respect to camera frame in the form of a transformation matrix (Hello!).

5 - Examine collision avoidance code and see if we can do better. Currently, the robot threshold a collision at 0.4 meter and do a random walk biased toward the opposite side of the detected collision. Front and left sonar sensor count as the left side.

Thanks,

An

**Comment by MCBurbage** [comment]
We also need someone to work on sending an image of the home circle april tag when a swarmie returns a tag to home.  This is a new rule for the competition.
MCB

```
  From: An Nguyen <notifications@github.com>
```

 To: UH-ECE6397/Swarmathon-ROS Swarmathon-ROS@noreply.github.com 
Cc: MCBurbage mcfieler@uh.edu
 Sent: Tuesday, March 8, 2016 3:24 PM
 Subject: Re: [Swarmathon-ROS] ROS meeting Monday (#10)

Hey guys,There weren't many undergraduates at the meeting yesterday. It's exam week, so y'all gotta study. No worries.We have started dividing up some work among the students. Each task will be created as an open issue that can be used as communication channels. Feel free to chime in if you would like to join the task.1 - State Machine analysis - Kaisong, Jordan and Mehmet2 - New messages and basic algorithm - An and Mary3 - Extended Kalman Filter (EKF) - Shiva and SrikanthThere are more tasks that have not been assigned, let us know if you would be interested in working on one of these:4 - Work to extract more information out of the April Tag library (UNM is using the April tag library from the creator of Arpil tags). It seems you can extract orientation and position of the tag with respect to camera frame in the form of a transformation matrix (Hello!).5 - Examine collision avoidance code and see if we can do better. Currently, the robot threshold a collision at 0.4 meter and do a random walk biased toward the opposite side of the detected collision. Front and left sonar sensor count as the left side.Thanks,An—
