### ISSUE TITLE
state machine diagrams

### ISSUE THREAD

**Issue by meakdogan** [UH-ECE6397/Swarmathon-ROS#18]
hello, @AlpNov  @fankaisong @Jordan-M-Bowman  state machine diagrams are posted. please check it if somethings is wrong.
transformating pdf has two pages and first page is target detection and collection, second is transformation machine state diagram
[trasformating state machine.pdf](https://github.com/UH-ECE6397/Swarmathon-ROS/files/201727/trasformating.state.machine.pdf)
[rotate machine.pdf](https://github.com/UH-ECE6397/Swarmathon-ROS/files/201726/rotate.machine.pdf)
[obstacle.pdf](https://github.com/UH-ECE6397/Swarmathon-ROS/files/201728/obstacle.pdf)

**Comment by AlpNov** [comment]
Please post this as a reply to the issue thread already existed.
