### ISSUE TITLE
Robot Arm Missing Parts

### ISSUE THREAD

**Issue by AlpNov** [UH-ECE6397/Swarmathon-ROS#3]
@UH-ECE6397/students @UH-ECE6397/staff 

This issue thread is for teams to report what part numbers they are missing for their robot arm. We'll try to get the missing parts cut by next Monday. Also if you have problems with your robots such as not moving in its full range of motion.

**Comment by chandikasilva** [comment]
My team needs Part 3

**Comment by AlpNov** [comment]
We'll have the new parts to you tomorrow.

Class is optional tomorrow. We'll meet for people who want to finish their robot arms.

An

**Comment by AlpNov** [comment]
https://youtu.be/J7YuxXWryqU

A preview of what the robot arm.

**Comment by arunvece** [comment]
Great clip An. Thanks for the share. 

Sent from Yahoo Mail on Android 

  On Fri, Feb 12, 2016 at 2:47 PM, An Nguyennotifications@github.com wrote:  
https://youtu.be/J7YuxXWryqU

A preview of what the robot arm.

**Comment by phatnguyenUH** [comment]
An, can we get part number 21, and number 5

**Comment by AlpNov** [comment]
Yes come to the lab after 10.

An
